remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: [Rafn Árnason]
description: [asdf]
Additionally, you may choose to set the following optional variables:

show_downloads: [false]
google_analytics: [12345]
